version: "3"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ./opencart/upload:/var/www/html

  nginx:
    image: nginx:alpine
    volumes:
      - ./opencart/upload:/var/www/html
      - ./docker/nginx/php.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    image: mariadb
    env_file:
      - ./docker/db.env
    ports:
      - "3306:3306"